<?php

/**
 * GoogleTranslator for PHP - library for translating text via Google Translator API.
 *
 * @author     David Grudl
 * @copyright  Copyright (c) 2010 David Grudl
 * @license    New BSD License
 * @link       http://phpfashion.com/
 * @version    1.0
 */
class GoogleTranslator
{

	/** @var string  source lang */
	private $srcLang;

	/** @var string  destination lang */
	private $destLang;



	/**
	 * @param  string   source language (optional)
	 * @param  string   destination language
	 */
	public function __construct($srcLang, $destLang)
	{
		$this->srcLang = $srcLang;
		$this->destLang = $destLang;
	}



	/**
	 * Translates text.
	 * @param  string
	 * @return string
	 * @throws GoogleTranslatorException
	 */
	public function translate($text)
	{
		$options = array(
			'http' => array(
				'method' => 'POST',
				'timeout' => 20,
				'content' => http_build_query(array(
					'v' => '1.0',
					'langpair' => "$this->srcLang|$this->destLang",
					'q' => (string) $text
				), '', '&'),
			),
		);

		$f = @fopen('http://ajax.googleapis.com/ajax/services/language/translate', 'r', FALSE, stream_context_create($options));
		if (!$f) {
			throw new GoogleTranslatorException('Server error');
		}

		$json = @json_decode(stream_get_contents($f)); // intentionally @
		if (!isset($json->responseData->translatedText)) {
			throw new GoogleTranslatorException('Invalid server response');
		}

		return $json->responseData->translatedText;
	}

}



/**
 * An exception generated by GoogleTranslator.
 */
class GoogleTranslatorException extends Exception
{
}
